# Template for Streamlit Secrets
# Rename this file to secrets.toml and add your actual API key

# OpenAI API Key
openai_api_key = "your-openai-api-key"

# Add other secrets here if needed

[general]
# Hier können weitere Konfigurationseinstellungen hinzugefügt werden
default_template = "Klassisch"
show_extracted_text = false 